name: flutter_midi_command_platform_interface
description: A common platform interface for the FlutterMidiCommand plugin.
version: 0.2.1
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter